framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        routing:
            'App\Modules\Shared\Domain\DomainEvent': [sync, async]

        default_bus: command.bus
        buses:
            query.bus:

            command.bus:

            event.bus:
                default_middleware: allow_no_handlers
